### ISSUE TITLE
hex representation does not work.

### ISSUE THREAD

**Issue by hyotang666** [pnathan/cl-ansi-text#15]
README says

> These are CSS-style color strings such as "#FF0000".

but it does not work.

```lisp
(with-color ("#ff0000") (princ :hoge)) => error

(with-color ("ff0000") (princ :hoge)) => works
```

If documentation is expected one, `cl-colors2:parse-hex-rgb` should be used rather than `cl-colors2:hex-to-rgb` in the method `RGB-COLOR-CODE`.

If current behavior is expected one, the readme should be fixed.

**Comment by pnathan** [comment]
Good catch! Thanks for the report.

Regards,
Paul
