### ISSUE TITLE
Introduce style-sheets and some other stuff

### ISSUE THREAD

**Issue by mrkkrp** [pnathan/cl-ansi-text#6]
Current API can be improved. Imagine that we could have some style table, so you could associate a keyword with collection of parameters: color, effects, etc. Once it's done, we could use these keywords to control style of output. Even more: this should be the only one way to color output. This way you don't repeat yourself if you have to follow some consistent style through your program. Every item in such a style table can be easily edited that will result in different rendering of all text that uses this style.

More interesting functions may be added. For example, something that sets fill-column, although it's nothing to do with ANSI terminals.

It's interesting what you can say about these ideas, because I see that your library is not bad. If you don't want to include these features, I will write my own library that is based on the idea of style-sheets.

**Comment by pnathan** [comment]
Hmm!

I like that idea!

What do you think of providing a second DEFSYSTEM in this library? (Cl-ansi-textstyles perhaps?)

**Comment by mrkkrp** [comment]
That would be the right thing to do... I've studied your code, this existing code should be used as a base for this new system. I think that single `make-color-string` function is everything we need.

The idea of style-sheets is good, but better API is also needed. This is just as important as style-sheets. How to colorize different fragments of text easily? Well, here is one idea, based on `format` function. By the way, you could really improve examples in README.md using format:
```
(format t "~a test results went ~a!" (yellow "Five") (red "terribly wrong"))
```
It's way more readable. Furthermore, this format function gives us an example of how to organize colorized output. Imagine that we have the following keywords that denote some styles: `:number`, `:base`, and `:error`. Now, what if we wrote `format`, that would work just like `format`, but would also allow us to specify style for every element:
```
(format (t :base)
        "~a test results went ~a!"
        ("Five" :number)
        ("terribly wrong" :error))
```
every `car` could be anything: number, string, symbol, etc. `cadr` should be a keyword that denotes style that should have been defined in a style sheet. Some default cases are also necessary, so we could supply not only lists, but also simple elements, their style should default to something.

How can we further improve this? Well, there are many things to include in 'style' that have nothing to do with ANSI terminals, but are useful for nice terminal output. This is a different topic.

Now I have one most important question to answer, whether it's better to extend your library or to write minimal separate library that have no 'extra' functions or systems. You see, I would like to extend your library, but the more I think about it the more it feels like two very different libraries will coexist under one name. If you like these ideas, feel free to use any of them and improve your library, however I think I should try to write my own.

**Comment by pnathan** [comment]
I agree - this seems like a great incremental library on top of `cl-ansi-text`, not an extension of `cl-ansi-text` itself.

I am fine adding it as a secondary library as part of this codebase if you send in a pull request.
