### ISSUE TITLE
CCL: No MAKE-LOAD-FORM method is defined for #S(CL-COLORS:RGB :RED 38/51 :GREEN 38/51 :BLUE 38/51)

### ISSUE THREAD

**Issue by avodonosov** [pnathan/cl-ansi-text#7]
I often see this error:
```
 No COMMON-LISP:MAKE-LOAD-FORM method is defined for #S(CL-COLORS:RGB :RED 38/51 :GREEN 38/51 :BLUE 38/51)
```
Example log: http://cl-test-grid.appspot.com/blob?key=em5wzi7bnx

Many more examples can be found in this report:
https://common-lisp.net/project/cl-test-grid/ql/quicklisp-2015-06-08-diff2.html

As you see from the log, the error happens not when cl-ansi-text is compiled, but when another library depending on it is compiled, file quicklisp/dists/quicklisp/software/prove-20150113-git/src/reporter/list.lisp

Probably CCL tries to inline the `gray` constant in the client code. It's difficult to reproduce, I don't know how CCL makes the decision to inline.  Maybe it's even non-deterministic, on this page - http://trac.clozure.com/ccl/wiki/DeclareOptimize - we read: "If the lisp kernel profile shows a lot of time spent in _SPspecrefcheck, it might help to spend less time doing special variable references inline." Does it mean the compiler decides when to optimize depending on some profile statistics lisp kernel accumulates on runtime?  I don't know.

But anyway, just from the fact that the error happens when a dependent library is compiled, I suggest to 
add ` :load-toplevel :execute` to the `eval-when` here: https://github.com/pnathan/cl-ansi-text/blob/f618463c8c9f30c966e30831cea659b613a0431c/cl-ansi-text.lisp#L36

**Comment by pnathan** [comment]
Hm. that's no good.

I had a difficult time with CCL initially getting this library to function appropriately with cl-colors, as you can likely infer from the comment on line 28 in the referenced file.  

I should have some free time this week to close on this - I will of course be trying to get some tests done before I push the fix.

**Comment by avodonosov** [comment]
In principle you can just safely add `:load-toplevel :execute` to that `eval-when` and don't worry about anything.

It is 100% necessary that CCL needs this method not only for the `:compile-toplevel`. And this fix is not going to break anything.

I posted so just describe my attempt to understand why exactly CCL calls this method, but the solution is simple - just provide this method.

**Comment by pnathan** [comment]
Hi, implemented suggested fix.
